### ISSUE TITLE
Search button doesn't appear

### ISSUE THREAD

**Issue by megodoonch** [jgroschwitz/vulcan#8]
Running `visualize_amr_corpus` on the little prince dev set, when I first open the seaerch interface, there's no searh button. WHen I close the search and re-open it, the search button is present, and it tries to run a search when I click it.

**Comment by jgroschwitz** [comment]
Fixed (this was due to there being default search filters being loaded, a leftover from debugging, which caused the program to crash before the search button was drawn when using a corpus that did not match the default search filters)
