### ISSUE TITLE
Server error on search

### ISSUE THREAD

**Issue by megodoonch** [jgroschwitz/vulcan#9]
Searching while running  `visualize_amr_corpus` on the little prince dev set, searching usually throws a server error. 

Errors in the console include `Exception: Corpus slice not found: Sentence` and `return obj is not None and obj[0 ["node_label"].strip().lower() == user_arguments[0].strip().lower() AttributeError: 'NoneType' object has no attribute 'strip'`

**Comment by jgroschwitz** [comment]
I just found some unpushed changes on my laptop that seem to have fixed this issue. Could you try again with the most recent version to confirm?

**Comment by megodoonch** [comment]
Works!
